apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # The name of the deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: front-nginx # The name of the label of the service
  template: # Specify how to create the pod
    metadata:
        name: nginx-pod # The name of the pod
        labels:
          component: front-nginx # has to be similar as matchLabels and also similar the label in service
    spec:
      containers:
        - name: nginx-deployment
          image: nginx
          ports:
          - containerPort: 80 # This is the internal pod port which is mapped to the external port on my host. In case of node/npm it run as default on port 3000
