pipeline{
    agent any
    stages{
        stage('Cloning'){
            steps{
                git clone https://github.com/devopsPRO27/kub
            }
        stage('building') {
            steps{
                sh "npm install"
                sh "npm start"
            }
        }
            
        }
    }
}