pipeline{
    agent any
    stages{
        // stage('Cleaning'){
        //     steps{
        //         // Clean before build
        //         cleanWs()
        //     }
        // }
        stage('Cloning'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/eran8888/JenkinsGitandmore.git']]])
            }
        }
        stage('building'){
            steps{
                sh "cd '/var/jenkins_home/workspace/Hodi's homework kub@tmp/durable-d59dca3eHomework/K8S/docker-app'"
                sh "docker build -t npm:0.0.1"
                sh "docker run -p8082:3000 -t npm:0.0.1"
                sh "docker stop npm:0.0.1"
            }
        }
    }
}