apiVersion: v1
kind: Pod
metadata:
  name: client-pod1
  labels:
    name: client-pod1
    component: web1
spec:
  containers:
  - name: client-pod1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
